[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "omegaqe"
version = "0.0.2"
description = ""
authors = [
    "Mathew Robertson <mathew.robertson@sussex.ac.uk>",
    "Ewan Chamberlain <e.a.chamberlain@sussex.ac.uk>",
    "Raphael Kou <r.kou@sussex.ac.uk>"
]
packages = [{ include = "omegaqe" }, { include = "fullsky_sims"}]

[tool.poetry.dependencies]
python = ">=3.11"
numpy = ">=2"
healpy = "*"
scipy = ">=1.14"
lenspyx = "*"
vector = "0.8.5"
matplotlib = "*"
camb = "*"
ipykernel = "*"
pandas = "*"
delensalot = { path = "./submodules/delensalot", develop = true }
plancklens = { path = "./submodules/plancklens", develop = true }
lensit = { path = "./submodules/LensIt", develop = true }
lensitbiases = { path = "./submodules/lensitbiases", develop = true }

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    "*.ipynb",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Cobaya.
line-length = 90
indent-width = 4


[tool.ruff.lint]
# As Cobaya [without E704 :( ]
preview = true # some rules need this
select = ["E713","E703","E714","E741","E10","E11","E20","E22","E23","E25","E27","E301","E302","E304","E9","F405","F406","F5","F6","F7","F8","W1","W2","W3","W6"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
